const allPropertiesNames = [
    'uniqueID',
    'nickname',
    'phoneNumber',
    'birthDate',
    'description' ,
    'userTypeId',
    'sexualOrientationId',
    'hairColor',
    'titsSize',
    'heightInCentimeters',
    'weightInKilograms',
    'massagePreference',
    'vaginalSexPreference',
    'blowjobPreference',
    'oralCreampiePreference',
    'cumSwallowPreference',
    'cumOnFacePreference',
    'analPreference',
    'pussyLickingPreference',
    'clientRimmingPreference',
    'kissingPreference',
    'cumOnBodyPreference',
    'tripsPreference',
    'analAditionalPayment',
    'vaginalSexAditionalPayment',
    'blowjobAditionalPayment',
    'oralCreampieAditionalPayment',
    'cumOnFaceAditionalPayment',
    'massageAditionalPayment',
    'pussyLickingAditionalPayment',
    'clientRimmingAditionalPayment',
    'kissingAditionalPayment',
    'cumOnBodyAditionalPayment',
    'cumSwallowAditionalPayment',
    'secondaryServices',
    'paymentForms',
    'photos',
    'preciseHoursDecision',
    'showEverySingleWeekday',
    'workingHours',
    'citiesList',
    'cityId',
    'regionId',
];

export default allPropertiesNames;

export const optionalPersonalitiesPropertiesNames = [
    'phoneNumber',
    'description' ,
    'sexualOrientationId',
    'heightInCentimeters',
    'weightInKilograms',
    'hairColor',
    'titsSize',
    'height',
    'weight',
];

export const sexServicesAlwaysVisibleKeys = [
    'massage',
    'vaginalSex',
    'blowjob',
    'cumOnFace',
    'anal',
    'pussyLicking',
    'clientRimming',
    'kissing',
    'cumOnBody',
];
// 'oralCreampie',
// 'cumSwallow',

export const allMainSexServices = [
    ...sexServicesAlwaysVisibleKeys,
    'oralCreampie',
    'cumSwallow',
]